services:
  ticket-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vivaeventos-ticket-service
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ticket-db
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      SERVICES_ORDER_SERVICE_URL: http://172.20.0.1:8083
      SERVICES_EVENT_SERVICE_URL: http://172.20.0.1:8082
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres
      - rabbitmq
    restart: always

  postgres:
    image: postgres:15-alpine
    container_name: ticket-service-db
    restart: always
    environment:
      POSTGRES_DB: ticket-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: ticket-service-rabbitmq
    ports:
      - "5674:5672"
      - "15674:15672"
volumes:
  postgres_data:
