spring.application.name=vivaeventos-ticket-service
server.port=${SERVER_PORT:8085}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5436/ticket-db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

spring.profiles.active=rabbit

services.order-service.url=${SERVICES_ORDER_SERVICE_URL:http://localhost:8083}